--// ============================================================================
--// AirHub — 04_wallhack.lua
--// WallHack boxes (3D / 2D) + Glow + HUD + Self ESP (Chams + China Hat).
--// Requires: 01_core.lua, 02_aimbot.lua (
